services:
  - type: web
    name: clarity-metabase
    env: docker
    repo: https://github.com/render-examples/metabase.git # optional
    plan: standard
    autoDeploy: false
    envVars:
      - key: MB_DB_CONNECTION_URI
        fromDatabase:
          name: clarity-metabase-db
          property: connectionString
databases:
  - name: clarity-metabase-db
    databaseName: clarity_metabase_db
    plan: standard plus
    ipAllowList: [] # only allow internal connections
